# Generated by Django migration

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_gender'),
        ('clans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='clan',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='members',
                to='clans.clan',
                verbose_name='Клан'
            ),
        ),
    ]

