# Generated by Django migration

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='strength',
            field=models.IntegerField(default=1, help_text='Сила'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='intelligence',
            field=models.IntegerField(default=1, help_text='Интеллект'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='agility',
            field=models.IntegerField(default=1, help_text='Ловкость'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='stat_upgrade_points',
            field=models.IntegerField(default=0, help_text='Очки для прокачки показателей (дают при повышении уровня)'),
        ),
    ]
