# Generated by Django 5.2.6 on 2025-12-03 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerLandmarkObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField(auto_now_add=True)),
                ('landmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_observations', to='landmarks.landmark')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landmark_observations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-observed_at'],
                'unique_together': {('player', 'landmark')},
            },
        ),
    ]
