# Generated by Django 5.2.6 on 2025-12-03 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerLandmarkObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, help_text='ID достопримечательности из Wikipedia API', max_length=200, null=True)),
                ('observed_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landmark_observations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-observed_at'],
                'indexes': [models.Index(fields=['player', 'external_id'], name='landmarks_p_player__0c22d6_idx')],
                'unique_together': {('player', 'external_id')},
            },
        ),
    ]
