# Generated by Django 5.2.6 on 2025-12-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmarks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerlandmarkobservation',
            name='external_id',
            field=models.CharField(help_text='ID достопримечательности из Wikipedia API', max_length=200),
        ),
    ]
